### ISSUE TITLE
Devcontainer mounts

### ISSUE THREAD

**Issue by kurmann** [kurmann/videoschnitt#206]
Danke für die zusätzlichen Informationen. Da der äußere Docker-Container durch `devcontainer.json` definiert wird, müssen wir sicherstellen, dass die Verzeichnisse korrekt gemountet werden und dass die inneren Container Zugriff darauf haben.

### Schritte zur Implementierung

1. **Erstellen der Verzeichnisse auf dem Host-System**: Stelle sicher, dass die Verzeichnisse und Testdateien auf deinem Host-System vorhanden sind.
2. **Anpassen der `devcontainer.json`**: Passe die `devcontainer.json` an, um die Verzeichnisse korrekt zu mounten.
3. **Anpassen des inneren Docker-Compose-Files**: Passe das innere Docker-Compose-File an, um die Verzeichnisse korrekt zu mounten.

### 1. Erstellen der Verzeichnisse auf dem Host-System

Erstelle die Verzeichnisse auf deinem Host-System und füge Testdateien hinzu:

```sh
mkdir -p ~/Videoschnitt/Zur\ Mediathek
mkdir -p ~/Videoschnitt/Mediathek\ \(Simulation\)
touch ~/Videoschnitt/Zur\ Mediathek/testfile1.txt
touch ~/Videoschnitt/Mediathek\ \(Simulation\)/testfile2.txt
```

### 2. Anpassen der `devcontainer.json`

Passe die `devcontainer.json` Datei an, um die Verzeichnisse vom Host-System in den äußeren Container zu mounten:

```json
{
	"name": "Existing Dockerfile",
	"image": "mcr.microsoft.com/dotnet/nightly/sdk:9.0-preview-noble",
	"features": {
		"ghcr.io/devcontainers-contrib/features/ffmpeg-apt-get:1": {},
		"ghcr.io/devcontainers/features/github-cli:1": {},
		"ghcr.io/devcontainers/features/docker-in-docker:2": {}
	},
	"containerEnv": {
		"MetadataProcessing__InputDirectory": "/workspaces/videoschnitt/testdata"
	},
	"mounts": [
		"source=${localEnv:HOME}/Videoschnitt/Zur Mediathek,target=/workspace/Videoschnitt/Zur Mediathek,type=bind",
		"source=${localEnv:HOME}/Videoschnitt/Mediathek (Simulation),target=/workspace/Videoschnitt/Mediathek (Simulation),type=bind"
	],
	"customizations": {
		"vscode": {
			"extensions": [
				"GitHub.copilot",
				"GitHub.vscode-github-actions",
				"ms-dotnettools.csharp@1.26.0",
				"kreativ-software.csharpextensions"
			]
		}
	}
}
```

### 3. Anpassen des inneren Docker-Compose-Files

Passe das innere Docker-Compose-File an, um die Verzeichnisse im äußeren Container in die inneren Container zu mounten:

```yaml
version: '3.8'

services:
  videoschnitt:
    build: .
    container_name: videoschnitt
    volumes:
      - "/workspace/Videoschnitt/Zur Mediathek:/media/inputDirectory:rw"
      - "/workspace/Videoschnitt/Mediathek (Simulation):/media/infuseLibrary:rw"
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - Application__InputDirectory=/media/inputDirectory
      - Application__InfuseMediaLibraryPath=/media/infuseLibrary
      - PORT=8080
```

### Zusammenfassung

1. **Erstellen der Verzeichnisse auf dem Host-System**:
   ```sh
   mkdir -p ~/Videoschnitt/Zur\ Mediathek
   mkdir -p ~/Videoschnitt/Mediathek\ \(Simulation\)
   touch ~/Videoschnitt/Zur\ Mediathek/testfile1.txt
   touch ~/Videoschnitt/Mediathek\ \(Simulation\)/testfile2.txt
   ```

2. **Anpassen der `devcontainer.json`**:
   ```json
   {
	"name": "Existing Dockerfile",
	"image": "mcr.microsoft.com/dotnet/nightly/sdk:9.0-preview-noble",
	"features": {
		"ghcr.io/devcontainers-contrib/features/ffmpeg-apt-get:1": {},
		"ghcr.io/devcontainers/features/github-cli:1": {},
		"ghcr.io/devcontainers/features/docker-in-docker:2": {}
	},
	"containerEnv": {
		"MetadataProcessing__InputDirectory": "/workspaces/videoschnitt/testdata"
	},
	"mounts": [
		"source=${localEnv:HOME}/Videoschnitt/Zur Mediathek,target=/workspace/Videoschnitt/Zur Mediathek,type=bind",
		"source=${localEnv:HOME}/Videoschnitt/Mediathek (Simulation),target=/workspace/Videoschnitt/Mediathek (Simulation),type=bind"
	],
	"customizations": {
		"vscode": {
			"extensions": [
				"GitHub.copilot",
				"GitHub.vscode-github-actions",
				"ms-dotnettools.csharp@1.26.0",
				"kreativ-software.csharpextensions"
			]
		}
	}
}
   ```

3. **Anpassen des inneren Docker-Compose-Files**:
   ```yaml
   version: '3.8'

   services:
     videoschnitt:
       build: .
       container_name: videoschnitt
       volumes:
         - "/workspace/Videoschnitt/Zur Mediathek:/media/inputDirectory:rw"
         - "/workspace/Videoschnitt/Mediathek (Simulation):/media/infuseLibrary:rw"
       ports:
         - "8080:8080"
       environment:
         - ASPNETCORE_ENVIRONMENT=Production
         - Application__InputDirectory=/media/inputDirectory
         - Application__InfuseMediaLibraryPath=/media/infuseLibrary
         - PORT=8080
   ```

Diese Schritte sollten sicherstellen, dass die Verzeichnisse korrekt durch den äußeren und inneren Docker-Container hindurch gemountet sind. Wenn du weiterhin Probleme hast, lass es mich wissen, und wir können weitere Schritte zur Fehlerbehebung unternehmen.
