### ISSUE TITLE
log to file

### ISSUE THREAD

**Issue by kurmann** [kurmann/videoschnitt#39]

**Comment by kurmann** [comment]
Was ist mit den Docker logs? Wie kann ich sicherstellen, dass diese in einem Volume abgelegt werden und somit auch nach dem Entfernen des Containers noch zugänglich sind? Wie werden die Logs hinsichtlich Dateiaufteilung organisiert? Jeder Tag ein neues Log?

Das Protokollieren der Logs seitens .NET ist sichergestellt und das Abgreifen der logs mit docker logs -f <container-name> funktioniert. Es geht mir um die Persistierung

---

Um sicherzustellen, dass die Logs von Docker-Containern in einem Volume abgelegt werden und somit auch nach dem Entfernen des Containers zugänglich bleiben, kannst du die Logs in ein benanntes Volume oder ein Host-Verzeichnis umleiten. Hier ist eine Vorgehensweise, um dies zu erreichen:

### Schritt 1: `.env` Datei
```dotenv
LocalMediaLibrary__LibraryPath=/path/to/media/library
LogPath=/path/to/log/directory
```

### Schritt 2: `docker-compose.yml` Datei
```yaml
version: '3.8'

services:
  videoschnitt-kraftwerk:
    build: .
    container_name: videoschnitt-kraftwerk
    volumes:
      - logs:/app/logs
      - ${LocalMediaLibrary__LibraryPath}:/media/library:rw
      - ${LogPath}:/app/logs:rw
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - LOCAL_MEDIA_LIBRARY_PATH=/media/library
      - LOG_PATH=/app/logs

volumes:
  logs:
```

### Erklärung:
1. **.env Datei**:
   - `LocalMediaLibrary__LibraryPath` definiert den Pfad zum Medienverzeichnis auf dem Host.
   - `LogPath` definiert den Pfad zum Log-Verzeichnis auf dem Host.

2. **docker-compose.yml**:
   - Mountet das Verzeichnis `LocalMediaLibrary__LibraryPath` als Volume.
   - Mountet das Verzeichnis `LogPath` als Volume, um die Logs zu persistieren.
   - Setzt die Umgebungsvariable `LOG_PATH` im Container auf das gemountete Log-Verzeichnis `/app/logs`.

### Beispiel: Konfiguration von .NET Logging

Innerhalb deiner .NET-Anwendung kannst du sicherstellen, dass die Logs in das Verzeichnis `/app/logs` geschrieben werden, indem du den `FileLogger` entsprechend konfigurierst. Hier ist ein Beispiel:

#### `appsettings.json`
```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    },
    "File": {
      "Path": "/app/logs/myapp-{Date}.log",
      "RollingInterval": "Day"
    }
  }
}
```

#### `Program.cs`
```csharp
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Serilog;
using System;
using System.IO;

namespace YourNamespace
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var configuration = new ConfigurationBuilder()
                .SetBasePath(Directory.GetCurrentDirectory())
                .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
                .AddEnvironmentVariables()
                .Build();

            Log.Logger = new LoggerConfiguration()
                .ReadFrom.Configuration(configuration)
                .CreateLogger();

            try
            {
                Log.Information("Starting up");
                CreateHostBuilder(args).Build().Run();
            }
            catch (Exception ex)
            {
                Log.Fatal(ex, "Application start-up failed");
            }
            finally
            {
                Log.CloseAndFlush();
            }
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .UseSerilog() // Use Serilog for logging
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
    }
}
```

### Dateiaufteilung der Logs:
- Die Konfiguration im `appsettings.json`-Beispiel verwendet den Platzhalter `{Date}` für die Dateiaufteilung. Dadurch wird für jeden Tag eine neue Log-Datei erstellt.
- `RollingInterval` ist auf "Day" gesetzt, was bedeutet, dass jeden Tag eine neue Log-Datei erstellt wird.

### Zusammenfassung:
- Die Logs werden in einem Host-Verzeichnis oder einem benannten Volume abgelegt, wodurch sie auch nach dem Entfernen des Containers erhalten bleiben.
- Die .NET-Anwendung ist so konfiguriert, dass sie Logs in dieses Verzeichnis schreibt und tägliche Log-Dateien erstellt.
- Das `docker-compose.yml`-File sorgt dafür, dass das Log-Verzeichnis als Volume gemountet wird und somit persistiert wird.

Mit dieser Konfiguration sind deine Logs nach dem Entfernen des Containers weiterhin zugänglich und in einer sinnvollen Struktur organisiert.

**Comment by kurmann** [comment]
Jetzt übernimmt .NET das Schreiben der Logs. Gibt es eine Möglichkeit, dass Docker diese Aufgaben übernimmt. Diese muss nur die Docker Logs in eine Datei schreiben.

---

Ja, es gibt eine Möglichkeit, Docker die Aufgabe zu übertragen, die Container-Logs in eine Datei zu schreiben. Dies kann durch die Konfiguration des Docker-Daemons erfolgen, um die Logs in ein bestimmtes Verzeichnis auf dem Host zu schreiben. Hier ist ein detaillierter Ansatz, wie dies gemacht werden kann:

### Schritt 1: Docker Daemon Konfiguration ändern
Um die Docker-Logs in eine Datei auf dem Host zu schreiben, musst du die Log-Treiber-Einstellungen im Docker-Daemon konfigurieren.

#### Docker Daemon Konfiguration (JSON-Datei)
Bearbeite die Datei `/etc/docker/daemon.json` auf deinem Host-System und füge die Log-Konfiguration hinzu:

```json
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3",
    "path": "/path/to/log/directory"
  }
}
```

- **`log-driver`**: Setzt den Log-Treiber auf `json-file`, der die Logs in JSON-Dateien schreibt.
- **`max-size`**: Begrenzung der Log-Dateigröße auf 10 MB.
- **`max-file`**: Begrenzung auf 3 Log-Dateien (Rotation).
- **`path`**: Definiert den Pfad auf dem Host, wo die Logs gespeichert werden.

### Schritt 2: Docker Compose Konfiguration
In der `docker-compose.yml` Datei kannst du sicherstellen, dass der Container den Log-Treiber von Docker verwendet:

```yaml
version: '3.8'

services:
  videoschnitt-kraftwerk:
    build: .
    container_name: videoschnitt-kraftwerk
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - logs:/app/logs
      - ${LocalMediaLibrary__LibraryPath}:/media/library:rw
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - LOCAL_MEDIA_LIBRARY_PATH=/media/library

volumes:
  logs:
```

### Schritt 3: Docker Daemon neu starten
Nach dem Bearbeiten der Docker Daemon Konfiguration musst du den Docker Daemon neu starten, damit die Änderungen wirksam werden:

```sh
sudo systemctl restart docker
```

### Logs überprüfen
Die Logs werden nun in das Verzeichnis geschrieben, das du in der Docker Daemon Konfiguration angegeben hast (`/path/to/log/directory`).

### Zusammenfassung:
- **Docker Daemon Konfiguration**: Ändere die Konfiguration des Docker-Daemons, um den `json-file` Log-Treiber zu verwenden und die Logs in ein spezifisches Verzeichnis auf dem Host zu schreiben.
- **Docker Compose**: Stelle sicher, dass der Log-Treiber und die entsprechenden Optionen in der `docker-compose.yml` Datei definiert sind.
- **Neustart des Docker Daemons**: Starte den Docker Daemon neu, um die Änderungen zu übernehmen.

Mit dieser Konfiguration schreibt Docker die Logs des Containers in das spezifizierte Verzeichnis auf dem Host, wodurch die Persistenz der Logs sichergestellt wird.
