### ISSUE TITLE
do not listen to ports below 1024

### ISSUE THREAD

**Issue by kurmann** [kurmann/videoschnitt#62]
Der Fehler `System.Net.Sockets.SocketException (13): Permission denied` deutet darauf hin, dass der Container nicht die erforderlichen Berechtigungen hat, um auf Port 80 zu lauschen. Auf Unix-basierten Systemen (einschließlich Linux, das auf Synology NAS läuft) erfordert das Lauschen auf Ports unter 1024 in der Regel Root-Rechte.

### Lösung

Eine übliche Lösung besteht darin, einen höheren Port zu verwenden, z. B. 8080 oder 5000, der keine Root-Berechtigungen erfordert. Wir können den Container so konfigurieren, dass er auf einem höheren Port lauscht, und diesen Port dann über Docker Compose oder das Webportal weiterleiten.

### Schritt 1: `Program.cs` anpassen, um einen höheren Port zu verwenden

Ändere die Portkonfiguration in der `Program.cs`, um standardmäßig auf einem höheren Port (z. B. 5000) zu lauschen.

#### Program.cs

```csharp
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Components.Web;

namespace Kurmann.Videoschnitt.Application;

public class Program
{
    public static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);
        
        // Standardport auf 5000 setzen, kann durch Umgebungsvariable überschrieben werden
        var port = Environment.GetEnvironmentVariable("PORT") ?? "5000";
        builder.WebHost.UseUrls($"http://*:{port}");

        builder.Services.AddRazorPages();
        builder.Services.AddServerSideBlazor();

        var app = builder.Build();

        if (!app.Environment.IsDevelopment())
        {
            app.UseHsts();
        }

        app.UseHttpsRedirection();

        app.UseStaticFiles();

        app.UseRouting();

        app.MapBlazorHub();
        app.MapFallbackToPage("/_Host");

        app.Run();
    }
}
```

### Schritt 2: `docker-compose.yml` anpassen

Passe die `docker-compose.yml` Datei an, um den Container-Port auf einen höheren Port wie 5000 zu setzen und diesen Port auf dem Host verfügbar zu machen.

#### docker-compose.yml

```yaml
version: '3.8'

services:
  videoschnitt-app:
    image: videoschnitt-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:5000"  # Leitet den Container-Port 5000 auf Host-Port 8080 weiter
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - PORT=5000  # Optional: hier den Standardport setzen oder überschreiben
    volumes:
      - /volume1/data-protection-keys:/keys  # Optional: Mount für Data Protection Keys
```

### Schritt 3: Docker-Container neu starten

Baue das Docker-Image und starte den Container neu, damit die Änderungen wirksam werden.

```bash
cd /path/to/your/docker-compose-directory
docker-compose down
docker-compose up -d
```

### Webportal verwenden

Nachdem der Container mit den neuen Einstellungen läuft, kannst du das Webportal verwenden, um die Ports zu konfigurieren. Wähle den Container und setze die Weiterleitung von 8080 auf 5000.

### Zusammenfassung

Durch die Verwendung eines höheren Ports wie 5000 vermeidest du das Problem mit den erforderlichen Root-Rechten. Die Anwendung wird auf diesem höheren Port laufen, und du kannst die Portweiterleitung sowohl in Docker Compose als auch im Synology Webportal konfigurieren, um sicherzustellen, dass sie über `http://<IP_DEINES_SYNOLOGY>:8080` zugänglich ist.

Falls du noch weitere Fragen hast oder zusätzliche Unterstützung benötigst, lass es mich wissen!
