### ISSUE TITLE
System-wide installation

### ISSUE THREAD

**Issue by kurmann** [kurmann/videoschnitt#656]

**Comment by kurmann** [comment]
Dein aktuelles `pyproject.toml`-File sieht schon gut aus, aber ich sehe ein paar Punkte, die du möglicherweise anpassen musst, um sicherzustellen, dass dein Paket korrekt als systemweites CLI-Tool installiert und ausgeführt werden kann.

Hier sind einige Verbesserungen, um sicherzustellen, dass alles funktioniert:

### 1. **Pfad zur Quelle**
   Du verwendest die Anweisung `[tool.setuptools.packages.find]`, um anzugeben, dass deine Quellcode-Dateien im `src`-Verzeichnis liegen. Aber Poetry braucht auch diesen Hinweis, um den richtigen Pfad zu den Python-Paketen zu finden. Du musst Poetry explizit sagen, dass der Code im `src`-Ordner liegt. 

   Füge dazu in deinem `pyproject.toml` folgende Zeilen unter `[tool.poetry]` hinzu:
   ```toml
   [tool.poetry]
   packages = [
       { include = "kurmann_videoschnitt", from = "src" }
   ]
   ```

   **Erläuterung:** Das sorgt dafür, dass Poetry weiß, wo es nach deinem Paket suchen muss.

### 2. **CLI-Skripte**
   Die `scripts`-Sektion in deinem `pyproject.toml` sieht korrekt aus. Der Eintrag:
   ```toml
   [tool.poetry.scripts]
   kurmann-videoschnitt = "kurmann_videoschnitt.app:app"
   ```
   sorgt dafür, dass ein Kommando namens `kurmann-videoschnitt` erzeugt wird, das auf `kurmann_videoschnitt.app:app` verweist. Dabei setzt es voraus, dass in der Datei `app.py` eine Typer- oder Click-App-Instanz (`app`) definiert ist. Wenn das der Fall ist, passt dieser Eintrag.

   Falls du anstelle von `app` eine Hauptfunktion (`main`) hast, die das CLI starten soll, musst du den Eintrag anpassen, z. B.:
   ```toml
   [tool.poetry.scripts]
   kurmann-videoschnitt = "kurmann_videoschnitt.app:main"
   ```

### 3. **Anpassungen für pip**
   Um sicherzustellen, dass `pip install .` dein Paket korrekt installiert, musst du sicherstellen, dass Poetry beim Bauen alle nötigen Daten einbezieht. Insbesondere ist es wichtig, dass die Paketquellen korrekt verlinkt sind, damit `pip` weiß, wo der Code liegt.

   Falls deine Quellen wie erwähnt in einem `src`-Ordner liegen, solltest du sicherstellen, dass auch der `src`-Ordner korrekt in die Distribution eingeschlossen wird. Deine aktuelle Konfiguration sieht gut aus, wenn du die oben erwähnten Anpassungen unter **Punkt 1** machst.

### 4. **Beispiel einer vollständigen `pyproject.toml`**

Hier ein angepasstes und vollständiges Beispiel für deine `pyproject.toml`:

```toml
[tool.poetry]
name = "kurmann-videoschnitt"
authors = ["Patrick Kurmann <kurmannwillisau@gmail.com>"]
version = "0.51.0"
description = "Sammlung von Werkzeugen zur Automatisierung im privaten Videoschnitt"
readme = "README.md"
license = "Apache-2.0"
packages = [
    { include = "kurmann_videoschnitt", from = "src" }
]

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
click = "^8.1.7"
python-dotenv = "^1.0.1"
typer = "^0.12.5"
osxmetadata = {version = "^1.3.5", python = ">=3.8,<3.13"}

[tool.poetry.scripts]
kurmann-videoschnitt = "kurmann_videoschnitt.app:app"
```

Mit diesen Änderungen solltest du in der Lage sein, das Paket mit `pip install .` zu installieren und es systemweit verfügbar zu machen.

### 5. **Testen der Installation**

Nach diesen Anpassungen kannst du testen, ob alles wie gewünscht funktioniert:

1. **Installiere dein Paket lokal:**
   ```bash
   pip install .
   ```

2. **Überprüfe die CLI-Verfügbarkeit:**
   ```bash
   kurmann-videoschnitt --help
   ```

Falls der Befehl funktioniert und die erwartete Ausgabe liefert, ist alles korrekt konfiguriert.

---

Ich muss aber die virtuelle Umgebung zuerst verlassen und dann Pip-Install ausführen, korrekt?

---

Ja, das ist korrekt. Wenn du möchtest, dass dein Paket systemweit und nicht nur innerhalb der aktuellen virtuellen Umgebung verfügbar ist, solltest du die virtuelle Umgebung zuerst verlassen. Hier ist der genaue Ablauf:

### 1. **Verlasse die virtuelle Umgebung**
   Wenn du gerade in einer virtuellen Umgebung mit Poetry arbeitest, verlässt du diese mit folgendem Befehl:

   ```bash
   exit
   ```

   Das bringt dich zurück in die systemweite Umgebung deines macOS.

### 2. **Installiere das Paket systemweit**
   Jetzt kannst du dein Paket systemweit installieren. Wechsle in dein Projektverzeichnis (dort, wo deine `pyproject.toml` liegt) und führe folgendes aus:

   ```bash
   pip install .
   ```

   Das installiert dein Paket systemweit, und das CLI sollte danach überall auf deinem System verfügbar sein.

### 3. **Überprüfe, ob das CLI verfügbar ist**
   Nachdem du die Installation abgeschlossen hast, kannst du prüfen, ob das CLI erfolgreich registriert wurde:

   ```bash
   kurmann-videoschnitt --help
   ```

Wenn das funktioniert, ist dein Paket korrekt systemweit installiert und das CLI-Kommando steht dir überall zur Verfügung.

Zusammengefasst:

- **Verlasse die virtuelle Umgebung.**
- **Installiere dein Paket systemweit mit `pip install .`.**
- **Teste, ob das CLI verfügbar ist.**
